In [ ]:
!wget https://github.com/EmilMaliev/Movie-Database/tree/977bf0a72a9af368906eb64b477f207c0f66b190/data

--2026-04-10 12:51:28--  https://github.com/EmilMaliev/Movie-Database/tree/977bf0a72a9af368906eb64b477f207c0f66b190/data
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘data’

data                    [  <=>               ] 224.00K   957KB/s    in 0.2s

2026-04-10 12:51:29 (957 KB/s) - ‘data’ saved [229372]

In [ ]:
!git clone https://github.com/EmilMaliev/Movie-Database.git

Cloning into 'Movie-Database'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 1), reused 11 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (15/15), 14.53 MiB | 9.79 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [ ]:
import pandas as pd
import numpy as np


movies=pd.read_csv('/content/Movie-Database/data/movies.csv',engine='python')

In [ ]:
movies.head()

,id,title,original_title,overview,release_date,runtime,budget,revenue,vote_average,vote_count,...,backdrop_path,status,tagline,homepage,original_language,adult,video,created_at,updated_at,genres
0,2,Ariel,Ariel,A Finnish man goes to the city to find a job a...,1988-10-21,73.0,0.0,0.0,7.102,368,...,/hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg,Released,NaN,NaN,fi,0,0,2026-02-13 12:09:05,2026-02-13T17:39:05.734678,"Drama,Comedy,Crime,Romance"
1,11,Star Wars,Star Wars,Princess Leia is captured and held hostage by ...,1977-05-25,121.0,11000000.0,775398007.0,8.202,21922,...,/2w4xG178RpB4MDAIfTkqAuSJzec.jpg,Released,"A long time ago in a galaxy far, far away...",http://www.starwars.com/films/star-wars-episod...,en,0,0,2026-02-13 10:49:07,2026-02-13T16:19:07.277805,"Adventure,Action,Science Fiction"
2,12,Finding Nemo,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",2003-05-30,100.0,94000000.0,940335536.0,7.817,20256,...,/eCynaAOgYYiw5yN5lBwz3IxqvaW.jpg,Released,There are 3.7 trillion fish in the ocean. They...,http://movies.disney.com/finding-nemo,en,0,0,2026-02-13 10:52:41,2026-02-13T16:22:41.330322,"Animation,Family"
3,13,Forrest Gump,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,142.0,55000000.0,677387716.0,8.462,29226,...,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,Released,The world will never be the same once you've s...,https://www.paramountmovies.com/movies/forrest...,en,0,0,2026-02-13 10:49:10,2026-02-13T16:19:10.070631,"Drama,Comedy,Romance"
4,14,American Beauty,American Beauty,"Lester Burnham, a depressed suburban father in...",1999-09-15,122.0,15000000.0,356296601.0,8.002,12792,...,/2ndw55F40IkALzWyjCCza3M6nqM.jpg,Released,... look closer,NaN,en,0,0,2026-02-13 11:14:17,2026-02-13T16:44:17.072753,Drama

In [ ]:
movies.describe()

           runtime        budget       revenue
count  9770.000000  9.770000e+03  9.770000e+03
mean     93.352293  1.736675e+07  5.599369e+07
std      37.961344  4.041495e+07  1.634615e+08
min       0.000000  0.000000e+00  0.000000e+00
25%      86.000000  0.000000e+00  0.000000e+00
50%      97.000000  0.000000e+00  0.000000e+00
75%     112.000000  1.400000e+07  2.482810e+07
max     650.000000  4.899000e+08  2.923706e+09

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9771 entries, 0 to 9770
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 9771 non-null   object
 1   title              9771 non-null   object
 2   original_title     9771 non-null   object
 3   overview           9611 non-null   object
 4   release_date       9710 non-null   object
 5   runtime            9770 non-null   float64
 6   budget             9770 non-null   float64
 7   revenue            9770 non-null   float64
 8   vote_average       9770 non-null   object
 9   vote_count         9770 non-null   object
 10  popularity         9770 non-null   object
 11  poster_path        9433 non-null   object
 12  backdrop_path      8252 non-null   object
 13  status             9770 non-null   object
 14  tagline            5968 non-null   object
 15  homepage           3434 non-null   object
 16  original_language  9770 non-null   object
 17  adult              9770 non-null   object
 18  video              9770 non-null   object
 19  created_at         9769 non-null   object
 20  updated_at         9769 non-null   object
 21  genres             9501 non-null   object
dtypes: float64(3), object(19)
memory usage: 1.6+ MB

In [ ]:
movies_df=movies.drop(columns=['original_title','release_date','vote_count','poster_path','backdrop_path','homepage','created_at','updated_at','original_language'])

In [ ]:
movies_df=movies_df[movies_df['popularity']!='Released']
movies_df=movies_df.reset_index(drop=True)

In [ ]:
movies_df

,id,title,overview,runtime,budget,revenue,vote_average,popularity,status,tagline,adult,video,genres
0,2,Ariel,A Finnish man goes to the city to find a job a...,73.0,0.0,0.0,7.102,5.0295,Released,NaN,0,0,"Drama,Comedy,Crime,Romance"
1,11,Star Wars,Princess Leia is captured and held hostage by ...,121.0,11000000.0,775398007.0,8.202,23.1666,Released,"A long time ago in a galaxy far, far away...",0,0,"Adventure,Action,Science Fiction"
2,12,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",100.0,94000000.0,940335536.0,7.817,15.7935,Released,There are 3.7 trillion fish in the ocean. They...,0,0,"Animation,Family"
3,13,Forrest Gump,A man with a low IQ has accomplished great thi...,142.0,55000000.0,677387716.0,8.462,22.7297,Released,The world will never be the same once you've s...,0,0,"Drama,Comedy,Romance"
4,14,American Beauty,"Lester Burnham, a depressed suburban father in...",122.0,15000000.0,356296601.0,8.002,8.6764,Released,... look closer,0,0,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,1618945,Yoh! Bestie,"Thando is perpetually unlucky in love, but whe...",95.0,0.0,0.0,6.136,35.9333,Released,NaN,0,0,"Comedy,Romance"
9766,1620991,The Investigation of Lucy Letby,An engaging and thought-provoking look at Lucy...,95.0,0.0,0.0,6.45,12.3752,Released,NaN,0,0,"Crime,Documentary"
9767,1627792,Sagaran,As female motorcycle racer Mica and her mechan...,70.0,0.0,0.0,0.0,4.4471,Released,NaN,0,0,Drama
9768,1627796,Pansamantala,A story of a drunken dare that pulls best frie...,0.0,0.0,0.0,0.0,7.7596,Released,NaN,0,0,Drama
9769,1630155,Antes,NaN,0.0,0.0,0.0,4.0,6.2573,Released,NaN,0,0,NaN

In [ ]:
movies_df['popularity']=movies_df['popularity'].astype('float')
movies_df['vote_average']=movies_df['vote_average'].astype('float')
movies_df['id']=movies_df['id'].astype(int)

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9770 entries, 0 to 9769
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            9770 non-null   int64
 1   title         9770 non-null   object
 2   overview      9610 non-null   object
 3   runtime       9769 non-null   float64
 4   budget        9769 non-null   float64
 5   revenue       9769 non-null   float64
 6   vote_average  9769 non-null   float64
 7   popularity    9769 non-null   float64
 8   status        9769 non-null   object
 9   tagline       5967 non-null   object
 10  adult         9769 non-null   object
 11  video         9769 non-null   object
 12  genres        9501 non-null   object
dtypes: float64(5), int64(1), object(7)
memory usage: 992.4+ KB

In [ ]:
movies_df.describe()

           runtime        budget       revenue  vote_average   popularity
count  9769.000000  9.769000e+03  9.769000e+03   9769.000000  9769.000000
mean     93.361142  1.736853e+07  5.599942e+07      5.461451     6.650083
std      37.953207  4.041664e+07  1.634689e+08      2.321010     9.365631
min       0.000000  0.000000e+00  0.000000e+00      0.000000     1.177400
25%      86.000000  0.000000e+00  0.000000e+00      5.000000     4.360100
50%      97.000000  0.000000e+00  0.000000e+00      6.152000     4.995000
75%     112.000000  1.400000e+07  2.482964e+07      6.924000     6.349500
max     650.000000  4.899000e+08  2.923706e+09     10.000000   365.031000

In [ ]:
num_coll=['runtime','budget','revenue','vote_average','popularity']

In [ ]:
cat_coll=['status','adult','video']

In [ ]:
str_coll=['title','overview','tagline']

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc=OneHotEncoder(sparse_output=False,drop='first').set_output(transform="pandas")

In [ ]:
movies_cat_onehot=enc.fit_transform(movies_df[cat_coll])

In [ ]:
movies_df

,id,title,overview,runtime,budget,revenue,vote_average,popularity,status,tagline,adult,video,genres
0,2,Ariel,A Finnish man goes to the city to find a job a...,73.0,0.0,0.0,7.102,5.0295,Released,NaN,0,0,"Drama,Comedy,Crime,Romance"
1,11,Star Wars,Princess Leia is captured and held hostage by ...,121.0,11000000.0,775398007.0,8.202,23.1666,Released,"A long time ago in a galaxy far, far away...",0,0,"Adventure,Action,Science Fiction"
2,12,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",100.0,94000000.0,940335536.0,7.817,15.7935,Released,There are 3.7 trillion fish in the ocean. They...,0,0,"Animation,Family"
3,13,Forrest Gump,A man with a low IQ has accomplished great thi...,142.0,55000000.0,677387716.0,8.462,22.7297,Released,The world will never be the same once you've s...,0,0,"Drama,Comedy,Romance"
4,14,American Beauty,"Lester Burnham, a depressed suburban father in...",122.0,15000000.0,356296601.0,8.002,8.6764,Released,... look closer,0,0,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,1618945,Yoh! Bestie,"Thando is perpetually unlucky in love, but whe...",95.0,0.0,0.0,6.136,35.9333,Released,NaN,0,0,"Comedy,Romance"
9766,1620991,The Investigation of Lucy Letby,An engaging and thought-provoking look at Lucy...,95.0,0.0,0.0,6.450,12.3752,Released,NaN,0,0,"Crime,Documentary"
9767,1627792,Sagaran,As female motorcycle racer Mica and her mechan...,70.0,0.0,0.0,0.000,4.4471,Released,NaN,0,0,Drama
9768,1627796,Pansamantala,A story of a drunken dare that pulls best frie...,0.0,0.0,0.0,0.000,7.7596,Released,NaN,0,0,Drama
9769,1630155,Antes,NaN,0.0,0.0,0.0,4.000,6.2573,Released,NaN,0,0,NaN

In [ ]:
movies_cat_onehot

,status_In Production,status_Planned,status_Post Production,status_Released,status_Rumored,status_None,adult_None,video_None
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
9765,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9766,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9767,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9768,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9769,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
movies_df['genres']=movies_df['genres'].fillna(value='Film')

In [ ]:
movies_df['genres']=movies_df['genres'].str.split(',')

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

multi_enc=MultiLabelBinarizer()

In [ ]:

movies_multi = pd.DataFrame(
    multi_enc.fit_transform(movies_df['genres']),
    columns=multi_enc.classes_,
    index=movies_df.index
)

In [ ]:
movies_multi

,Action,Adventure,Animation,Comedy,Crime,Documentary,Drama,Family,Fantasy,Film,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
9766,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9767,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
9768,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
9769,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
movies_cat_encoded=pd.concat([movies_cat_onehot,movies_multi],axis=1)

In [ ]:
movies_cat_encoded

,status_In Production,status_Planned,status_Post Production,status_Released,status_Rumored,status_None,adult_None,video_None,Action,Adventure,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,...,0,0,0,0,0,1,0,0,0,0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,1,0,0,0,0,0
9766,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9767,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9768,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9769,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler().set_output(transform='pandas')

In [ ]:
movies_df_standard=sc.fit_transform(movies_df[num_coll])

In [ ]:
movies_df_preproc_without_str=pd.concat([movies_df_standard,movies_cat_encoded],axis=1)

In [ ]:
movies_df_preproc_without_str=pd.concat([movies_df['id'],movies_df_preproc_without_str],axis=1)

In [ ]:
movies_df_preproc_without_str

,id,runtime,budget,revenue,vote_average,popularity,status_In Production,status_Planned,status_Post Production,status_Released,...,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,2,-0.536508,-0.429759,-0.342587,0.706862,-0.173044,0.0,0.0,0.0,1.0,...,0,0,0,0,1,0,0,0,0,0
1,11,0.728272,-0.157580,4.401053,1.180817,1.763614,0.0,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,0,0
2,12,0.174931,1.896135,5.410088,1.014933,0.976323,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
3,13,1.281614,0.931136,3.801457,1.292843,1.716963,0.0,0.0,0.0,1.0,...,0,0,0,0,1,0,0,0,0,0
4,14,0.754622,-0.058606,1.837123,1.094644,0.216368,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,1618945,0.043183,-0.429759,-0.342587,0.290642,3.126828,0.0,0.0,0.0,1.0,...,0,0,0,0,1,0,0,0,0,0
9766,1620991,0.043183,-0.429759,-0.342587,0.425935,0.611321,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
9767,1627792,-0.615556,-0.429759,-0.342587,-2.353170,-0.235232,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
9768,1627796,-2.460027,-0.429759,-0.342587,-2.353170,0.118473,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
9769,1630155,-2.460027,-0.429759,-0.342587,-0.629694,-0.041941,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)

In [ ]:
movies_df['overview']=movies_df['overview'].astype('str')

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
movies_df['tagline']=movies_df['tagline'].astype('str')

sentences = movies_df['overview'].tolist()
sentences = movies_df['tagline'].tolist()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(9770, 384)

In [ ]:
embeddings = model.encode(sentences)
emb_df_tags = pd.DataFrame(embeddings,index=movies_df.index)
print(emb_df_tags.shape)

(9770, 384)

In [ ]:
emb_df_tags

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,0.190121,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
1,-0.185302,0.498558,0.107955,-0.039881,0.007121,-0.326613,-0.386915,-0.161644,0.248238,-0.223956,...,0.060217,-0.202162,-0.381060,-0.199662,-0.176267,0.179358,0.131627,-0.065997,0.003417,-0.322912
2,-0.007759,-0.342391,0.242657,-0.192914,-0.074466,-0.387685,-0.271694,-0.162308,0.299610,-0.151871,...,0.166300,0.314694,0.053397,-0.336803,-0.407227,0.118451,-0.118140,-0.273417,0.229712,0.111050
3,-0.288409,-0.230829,0.117130,-0.070135,0.209546,-0.045856,-0.001102,-0.213387,0.354293,0.005298,...,0.196526,-0.016298,-0.383441,-0.156264,-0.339136,0.143742,-0.399492,-0.341885,0.119212,-0.051220
4,0.222239,-0.267198,0.083733,0.124244,0.270293,-0.036249,-0.127416,-0.107897,0.352191,-0.072725,...,0.185024,-0.237187,-0.180591,-0.037377,-0.741600,0.467566,0.054673,0.081468,0.066222,0.239145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,0.190121,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9766,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,0.190121,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9767,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,0.190121,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9768,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,0.190121,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9769,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,0.190121,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468

In [ ]:
emb_df_tags=pd.concat([movies_df['id'],emb_df_tags],axis=1)
emb_df_tags

,id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
0,2,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
1,11,-0.185302,0.498558,0.107955,-0.039881,0.007121,-0.326613,-0.386915,-0.161644,0.248238,...,0.060217,-0.202162,-0.381060,-0.199662,-0.176267,0.179358,0.131627,-0.065997,0.003417,-0.322912
2,12,-0.007759,-0.342391,0.242657,-0.192914,-0.074466,-0.387685,-0.271694,-0.162308,0.299610,...,0.166300,0.314694,0.053397,-0.336803,-0.407227,0.118451,-0.118140,-0.273417,0.229712,0.111050
3,13,-0.288409,-0.230829,0.117130,-0.070135,0.209546,-0.045856,-0.001102,-0.213387,0.354293,...,0.196526,-0.016298,-0.383441,-0.156264,-0.339136,0.143742,-0.399492,-0.341885,0.119212,-0.051220
4,14,0.222239,-0.267198,0.083733,0.124244,0.270293,-0.036249,-0.127416,-0.107897,0.352191,...,0.185024,-0.237187,-0.180591,-0.037377,-0.741600,0.467566,0.054673,0.081468,0.066222,0.239145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,1618945,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9766,1620991,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9767,1627792,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9768,1627796,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9769,1630155,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468

In [ ]:
emb_df_tags.to_csv('tagsline_embedding.csv',index=False)

In [ ]:
pd.read_csv('/content/tagsline_embedding.csv')

,id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
0,2,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
1,11,-0.185302,0.498558,0.107955,-0.039881,0.007121,-0.326614,-0.386915,-0.161644,0.248238,...,0.060217,-0.202162,-0.381060,-0.199662,-0.176267,0.179358,0.131627,-0.065997,0.003417,-0.322912
2,12,-0.007759,-0.342391,0.242657,-0.192914,-0.074466,-0.387685,-0.271694,-0.162308,0.299610,...,0.166300,0.314694,0.053397,-0.336803,-0.407227,0.118451,-0.118140,-0.273417,0.229712,0.111050
3,13,-0.288409,-0.230829,0.117130,-0.070135,0.209546,-0.045856,-0.001102,-0.213387,0.354293,...,0.196526,-0.016298,-0.383441,-0.156264,-0.339136,0.143742,-0.399492,-0.341885,0.119212,-0.051220
4,14,0.222239,-0.267198,0.083733,0.124244,0.270293,-0.036249,-0.127416,-0.107897,0.352191,...,0.185024,-0.237187,-0.180591,-0.037377,-0.741600,0.467566,0.054673,0.081468,0.066222,0.239145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,1618945,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9766,1620991,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9767,1627792,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9768,1627796,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468
9769,1630155,-0.154478,0.211953,0.024925,-0.011179,-0.183458,-0.082662,0.314431,0.219310,0.161344,...,0.124723,-0.017544,-0.178935,-0.149429,-0.232961,0.175983,0.285966,0.038492,-0.405116,0.055468

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=96)
emb_df_tags_pca=pca.fit_transform(emb_df_tags.drop('id',axis=1))
sum(pca.explained_variance_ratio_)

np.float32(0.88281155)

In [ ]:
emb_df_tags_pca=pd.DataFrame(emb_df_tags_pca)
emb_df_tags_pca

,0,1,2,3,4,5,6,7,8,9,...,86,87,88,89,90,91,92,93,94,95
0,2.505826,-0.015922,-0.053348,-0.026146,0.002313,0.014367,0.009309,0.003601,-0.011559,-0.001326,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
1,-1.870589,-0.152235,0.500117,0.242547,0.382791,-0.546074,1.988057,0.629168,-0.224262,0.639532,...,0.021445,0.484859,0.064413,0.062330,0.198396,-0.161915,0.285831,0.377646,0.000561,-0.035728
2,-1.561448,0.664410,-0.284182,0.070262,-0.305287,0.605071,0.300982,1.026879,-0.397308,-0.868485,...,0.332820,-0.956837,-0.291122,0.147027,-0.011388,-0.091632,-0.204046,-0.384638,-0.117716,0.042521
3,-2.255810,0.503846,-0.683723,-0.349542,0.060429,0.128908,1.545862,0.187917,0.101384,-0.486315,...,0.066695,0.137419,-0.348383,-0.009212,-0.520526,0.109112,0.006029,0.017685,-0.157300,-0.210509
4,-1.392542,0.395619,0.405455,0.700631,0.775104,-1.157958,-0.787666,-0.154724,-0.012499,0.705519,...,-0.333216,-0.162963,-0.191403,0.208280,0.000799,0.150031,0.187321,-0.269785,0.240245,-0.179596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,2.505826,-0.015922,-0.053348,-0.026146,0.002313,0.014367,0.009309,0.003601,-0.011559,-0.001326,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9766,2.505826,-0.015922,-0.053348,-0.026146,0.002313,0.014367,0.009309,0.003601,-0.011559,-0.001326,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9767,2.505826,-0.015922,-0.053348,-0.026146,0.002313,0.014367,0.009309,0.003601,-0.011559,-0.001326,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9768,2.505826,-0.015922,-0.053348,-0.026146,0.002313,0.014367,0.009309,0.003601,-0.011559,-0.001326,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9769,2.505826,-0.015922,-0.053348,-0.026146,0.002313,0.014367,0.009309,0.003601,-0.011559,-0.001326,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513

In [ ]:
movie_df_full=pd.concat([movies_df_preproc_without_str,emb_df_tags_pca],axis=1)
movie_df_full

,id,runtime,budget,revenue,vote_average,popularity,status_In Production,status_Planned,status_Post Production,status_Released,...,86,87,88,89,90,91,92,93,94,95
0,2,-0.536508,-0.429759,-0.342587,0.706862,-0.173044,0.0,0.0,0.0,1.0,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
1,11,0.728272,-0.157580,4.401053,1.180817,1.763614,0.0,0.0,0.0,1.0,...,0.021445,0.484859,0.064413,0.062330,0.198396,-0.161915,0.285831,0.377646,0.000561,-0.035728
2,12,0.174931,1.896135,5.410088,1.014933,0.976323,0.0,0.0,0.0,1.0,...,0.332820,-0.956837,-0.291122,0.147027,-0.011388,-0.091632,-0.204046,-0.384638,-0.117716,0.042521
3,13,1.281614,0.931136,3.801457,1.292843,1.716963,0.0,0.0,0.0,1.0,...,0.066695,0.137419,-0.348383,-0.009212,-0.520526,0.109112,0.006029,0.017685,-0.157300,-0.210509
4,14,0.754622,-0.058606,1.837123,1.094644,0.216368,0.0,0.0,0.0,1.0,...,-0.333216,-0.162963,-0.191403,0.208280,0.000799,0.150031,0.187321,-0.269785,0.240245,-0.179596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,1618945,0.043183,-0.429759,-0.342587,0.290642,3.126828,0.0,0.0,0.0,1.0,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9766,1620991,0.043183,-0.429759,-0.342587,0.425935,0.611321,0.0,0.0,0.0,1.0,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9767,1627792,-0.615556,-0.429759,-0.342587,-2.353170,-0.235232,0.0,0.0,0.0,1.0,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9768,1627796,-2.460027,-0.429759,-0.342587,-2.353170,0.118473,0.0,0.0,0.0,1.0,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513
9769,1630155,-2.460027,-0.429759,-0.342587,-0.629694,-0.041941,0.0,0.0,0.0,1.0,...,-0.000795,0.003830,0.001576,0.000001,0.001826,-0.001945,0.000632,-0.001681,0.003985,0.000513

In [ ]:
movie_df_full.to_csv('movie_df_full.csv',index=False)

In [ ]:
pip install annoy

Collecting annoy
  Downloading annoy-1.17.3.tar.gz (647 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.5/647.5 kB 13.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: annoy
  Building wheel for annoy (setup.py) ... done
  Created wheel for annoy: filename=annoy-1.17.3-cp312-cp312-linux_x86_64.whl size=549277 sha256=ea85a9a081a7fce26d5a639d1a9d21a3dc56ca930df2b599344d5ec97d959eb2
  Stored in directory: /root/.cache/pip/wheels/db/b9/53/a3b2d1fe1743abadddec6aa541294b24fdbc39d7800bc57311
Successfully built annoy
Installing collected packages: annoy
Successfully installed annoy-1.17.3

In [ ]:
from annoy import AnnoyIndex

movie_df_full_np=movie_df_full.drop('id',axis=1).to_numpy()
dim=movie_df_full_np.shape[1]
t = AnnoyIndex(dim, 'euclidean')
for i in range(movie_df_full_np.shape[0]):
    t.add_item(i, movie_df_full_np[i])
t.build(50,n_jobs=-1)
t.save('test.ann')

True

In [ ]:
query=np.random.random(dim)
u = AnnoyIndex(dim, 'euclidean')
u.load('test.ann') # super fast, will just mmap the file
indices = u.get_nns_by_vector(query, 10)
indices

[8125, 6103, 51, 5550, 4902, 1444, 6486, 342, 149, 217]

In [ ]:
def get_reccomendations(df:pd.DataFrame,id_list:list,index:str):
  tmp=df[df['id'].isin(id_list)].drop('id',axis=1).to_numpy()
  tmp=np.mean(tmp, axis=0)
  dim=tmp.shape[0]
  u = AnnoyIndex(dim, 'euclidean')
  u.load(index)
  indices = u.get_nns_by_vector(query, 10)
  ids=df['id'].iloc[indices].tolist()
  return  np.setdiff1d(ids, np.intersect1d(ids, id_list))

ids=get_reccomendations(movie_df_full,["2","12","115"],"/content/test.ann")
movies_df[movies_df['id'].isin(ids)]

,id,title,overview,runtime,budget,revenue,vote_average,popularity,status,tagline,adult,video,genres
149,380,Rain Man,When car dealer Charlie Babbitt learns that hi...,134.0,25000000.0,354825435.0,7.749,7.2860,Released,A journey through understanding and fellowship.,0,0,[Drama]
217,587,Big Fish,Throughout his life Edward Bloom has always be...,125.0,70000000.0,123200000.0,7.759,7.6918,Released,An adventure as big as life itself.,0,0,"[Adventure, Fantasy, Drama]"
342,841,Dune,"In the year 10,191, the most precious substanc...",136.0,40000000.0,31502434.0,6.179,9.7734,Released,"A world beyond your experience, beyond your im...",0,0,"[Adventure, Action, Science Fiction]"
1444,12429,Ponyo,"When Sosuke, a young boy who lives on a clifft...",100.0,34000000.0,202404009.0,7.757,9.1922,Released,Welcome to a world where anything is possible.,0,0,"[Fantasy, Animation, Family]"
4902,297222,PK,A stranger in the city asks questions no one h...,153.0,13000000.0,118920000.0,7.705,5.0856,Released,Peeke hai kya?,0,0,"[Drama, Comedy, Science Fiction]"
5550,378236,The Emoji Movie,"Gene, a multi-expressional emoji, sets out on ...",86.0,50000000.0,216909830.0,5.401,9.1742,Released,An adventure beyond words.,0,0,"[Animation, Comedy, Family]"
6103,454640,The Angry Birds Movie 2,"Red, Chuck, Bomb and the rest of their feather...",97.0,65000000.0,137792047.0,7.000,10.6160,Released,Frenemies unite.,0,0,"[Adventure, Animation, Comedy, Family]"
6486,514921,The Aeronauts,"In 1862, daredevil balloon pilot Amelia Wren t...",100.0,40000000.0,3485251.0,6.796,4.2913,Released,Soar beyond your limits.,0,0,"[Adventure, Drama, Romance]"
8125,951491,Saw X,"Between the events of 'Saw' and 'Saw II', a si...",118.0,13000000.0,125319714.0,7.185,9.9136,Released,Witness the return of Jigsaw.,0,0,"[Horror, Mystery]"

In [ ]:
cast=pd.read_csv('/content/Movie-Database/data/cast.csv')
cast['movie_id'].nunique()

9662

In [ ]:
cast['movie_id'].nunique()

9662

In [ ]:
group=cast.groupby('movie_id')['person_id'].agg(list)
group

movie_id
2          [54768, 54769, 4826, 54770, 1177496, 2493350, ...
11         [2, 3, 4, 5, 12248, 6, 130, 24343, 24342, 1515...
12         [13, 14, 12, 5293, 118, 18, 19, 6168, 17401, 1...
13         [31, 32, 33, 35, 34, 37821, 204997, 9640, 6751...
14         [1979, 516, 2155, 8210, 8211, 8212, 19, 2955, ...
                                 ...
1618945    [4293484, 4387180, 2385484, 3717457, 4387178, ...
1620991                                            [4870034]
1627792    [5420126, 1319939, 3126662, 3857648, 5981215, ...
1627796        [4463307, 5326859, 5600357, 5980949, 2252696]
1630155    [114254, 27462, 1063319, 225017, 592476, 51905...
Name: person_id, Length: 9662, dtype: object

In [ ]:
reviews=pd.read_csv('/content/Movie-Database/data/reviews.csv')
reviews

,id,movie_id,author,author_username,author_rating,content,created_at,updated_at,url,movie_title,movie_release_date,movie_rating,content_length
0,58a231c5925141179e000674,11,Cat Ellington,CatEllington,NaN,"(As I'm writing this review, Darth Vader's the...",2017-02-13T22:23:01.268Z,2021-06-23T15:57:53.915Z,https://www.themoviedb.org/review/58a231c59251...,Star Wars,1977-05-25,8.202,3429
1,5d340e7a2f8d090388d21ff2,11,John Chard,John Chard,10.0,A long time ago in a childhood not too far awa...,2019-07-21T07:04:26.939Z,2024-05-16T15:22:23.643Z,https://www.themoviedb.org/review/5d340e7a2f8d...,Star Wars,1977-05-25,8.202,2979
2,5e94ea4566565a0014baa6c5,11,gastyny,gastyny,10.0,Star Wars (1977) is a true masterpiece of cine...,2020-04-13T22:40:05.539Z,2021-06-23T15:58:36.846Z,https://www.themoviedb.org/review/5e94ea456656...,Star Wars,1977-05-25,8.202,564
3,60174e821b70ae003c643834,11,r96sk,r96sk,9.0,A quality start to the franchise.\n\nI say sta...,2021-02-01T00:42:42.135Z,2021-06-23T15:58:50.959Z,https://www.themoviedb.org/review/60174e821b70...,Star Wars,1977-05-25,8.202,1269
4,63c2163f05a53300e99bfdd1,11,GenerationofSwine,GenerationofSwine,10.0,Everyone and their mother is going to write re...,2023-01-14T02:41:03.836Z,2023-01-14T02:41:03.886Z,https://www.themoviedb.org/review/63c2163f05a5...,Star Wars,1977-05-25,8.202,2294
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13068,691e10cb8c18b5c8f5de5528,1539104,CinemaSerf,Geronimo1967,6.0,Whilst I do reckon that the cinema is a great ...,2025-11-19T18:47:39.233Z,2025-11-19T18:56:47.184Z,https://www.themoviedb.org/review/691e10cb8c18...,JUJUTSU KAISEN: Execution,2025-11-07,5.628,1192
13069,6906b031e3c847e5e44c85fb,1571470,DogsLoveMe,DogsLoveMe,1.0,When people say only attractive people are bei...,2025-11-02T01:13:21.140Z,2025-11-16T18:39:59.853Z,https://www.themoviedb.org/review/6906b031e3c8...,The Rats: A Witcher Tale,2025-10-29,5.390,193
13070,693cd86a011ca343dcaec713,1571470,jw,jw,2.0,"# LARPing the basic plot\n\nagain, Netflix cra...",2025-12-13T03:07:22.722Z,2025-12-13T03:11:20.395Z,https://www.themoviedb.org/review/693cd86a011c...,The Rats: A Witcher Tale,2025-10-29,5.390,1788
13071,6975a3ac2495071dfd10648a,1584215,MovieGuys,MovieGuys,5.0,"""Rather silly"" is my first and lasting reactio...",2026-01-25T05:01:32.390Z,2026-01-25T05:01:32.416Z,https://www.themoviedb.org/review/6975a3ac2495...,The Internship,2026-01-13,6.239,617
13072,6974feb3759aff6a60ab9632,1608982,Dean,Ditendra,7.0,**A Claustrophobic and Intense Survival Thrill...,2026-01-24T17:17:39.867Z,2026-01-24T17:22:12.225Z,https://www.themoviedb.org/review/6974feb3759a...,From the Ashes: The Pit,2026-01-21,4.071,2138

In [ ]:
reviews['author_rating']=reviews['author_rating'].fillna(0)

In [ ]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13073 entries, 0 to 13072
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  13073 non-null  object
 1   movie_id            13073 non-null  int64
 2   author              13073 non-null  object
 3   author_username     13073 non-null  object
 4   author_rating       13073 non-null  float64
 5   content             13073 non-null  object
 6   created_at          13073 non-null  object
 7   updated_at          13073 non-null  object
 8   url                 13073 non-null  object
 9   movie_title         13073 non-null  object
 10  movie_release_date  13073 non-null  object
 11  movie_rating        13073 non-null  float64
 12  content_length      13073 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 1.3+ MB

In [ ]:
len(reviews['author_username'].unique().tolist())

1703

In [ ]:
len(reviews['movie_id'].unique().tolist())

3752

In [ ]:
movie_voc={reviews['movie_id'].unique().tolist()[i]:i for i in range(len(reviews['movie_id'].unique().tolist()))}

In [ ]:
author_username_voc={reviews['author_username'].unique().tolist()[i]:i for i in range(len(reviews['author_username'].unique().tolist()))}

In [ ]:
import numpy as np

rating_matrix=np.zeros((len(reviews['author_username'].unique().tolist()),len(reviews['movie_id'].unique().tolist())))
rating_matrix.shape

(1703, 3752)

In [ ]:
for name in reviews['author_username'].unique().tolist():
  tmp=reviews[reviews['author_username']==name]['movie_id'].tolist()
  ratings=reviews[reviews['author_username']==name]['author_rating'].tolist()
  ind=0
  for i in tmp:
    rating_matrix[author_username_voc[name],movie_voc[i]]=ratings[ind]
    ind+=1

In [ ]:
matrix_df=pd.DataFrame(rating_matrix, columns=reviews['movie_id'].unique().tolist(),index=reviews['author_username'].unique().tolist())

In [ ]:
matrix_df

,11,12,13,14,15,18,19,22,24,28,...,1448560,1456349,1480382,1511789,1516391,1522377,1539104,1571470,1584215,1608982
CatEllington,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
John Chard,10.0,0.0,0.0,0.0,0.0,8.0,0.0,9.0,8.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
gastyny,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
r96sk,9.0,9.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GenerationofSwine,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
caseymoviemania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rhodora,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AbsoluteTube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mblom,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
Ina_77,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances

# считаем косинусное расстояние для пользователей и фильмов
user_similarity = pairwise_distances(matrix_df, metric='cosine')
item_similarity = pairwise_distances(matrix_df.T, metric='cosine')

In [ ]:
pd.DataFrame(user_similarity, index=matrix_df.index,columns=matrix_df.index)

,CatEllington,John Chard,gastyny,r96sk,GenerationofSwine,Geronimo1967,Floomeister2000,Dave09,johnmills,llgolden,...,judahmcfadden,rioangga69@gmail.com,geakin,alllaany,Contrarian,caseymoviemania,rhodora,AbsoluteTube,mblom,Ina_77
CatEllington,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
John Chard,1.0,2.220446e-16,0.941850,0.860079,0.836605,0.717509,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
gastyny,1.0,9.418504e-01,0.000000,0.953433,0.919900,0.965982,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
r96sk,1.0,8.600787e-01,0.953433,0.000000,0.855068,0.586424,1.0,1.0,0.955103,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
GenerationofSwine,1.0,8.366049e-01,0.919900,0.855068,0.000000,0.799056,1.0,1.0,0.997636,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
caseymoviemania,1.0,1.000000e+00,1.000000,1.000000,1.000000,0.973541,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
rhodora,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
AbsoluteTube,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mblom,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0
Ina_77,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.000000,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0

In [ ]:
pd.DataFrame(item_similarity)

,0,1,2,3,4,5,6,7,8,9,...,3742,3743,3744,3745,3746,3747,3748,3749,3750,3751
0,0.000000,5.582490e-01,0.814254,1.0,7.530537e-01,0.635557,0.738429,0.530640,0.623376,0.610465,...,1.0,0.769717,0.759881,1.0,1.0,1.0,0.581282,1.000000e+00,1.0,1.0
1,0.558249,1.110223e-16,0.795246,1.0,6.840339e-01,0.823011,0.711662,0.786957,0.832695,0.834037,...,1.0,0.746151,0.735309,1.0,1.0,1.0,0.538434,1.000000e+00,1.0,1.0
2,0.814254,7.952460e-01,0.000000,1.0,8.855390e-01,0.829897,0.722881,0.795246,0.839204,0.840494,...,1.0,0.756029,0.745608,1.0,1.0,1.0,0.556393,1.000000e+00,1.0,1.0
3,1.000000,1.000000e+00,1.000000,0.0,1.000000e+00,1.000000,1.000000,0.742468,1.000000,1.000000,...,1.0,1.000000,1.000000,1.0,1.0,1.0,1.000000,1.000000e+00,1.0,1.0
4,0.753054,6.840339e-01,0.885539,1.0,1.110223e-16,0.901060,0.579765,0.880905,0.812947,0.793620,...,1.0,0.655372,0.852033,1.0,1.0,1.0,0.741977,1.000000e+00,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3747,1.000000,1.000000e+00,1.000000,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.0,1.0,0.0,1.000000,1.000000e+00,1.0,1.0
3748,0.581282,5.384337e-01,0.556393,1.0,7.419766e-01,0.616546,0.375305,0.538434,0.637527,0.640434,...,1.0,0.450028,0.426538,1.0,1.0,1.0,0.000000,1.000000e+00,1.0,1.0
3749,1.000000,1.000000e+00,1.000000,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.0,1.0,1.0,1.000000,1.110223e-16,1.0,1.0
3750,1.000000,1.000000e+00,1.000000,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.0,1.000000,1.000000,1.0,1.0,1.0,1.000000,1.000000e+00,0.0,1.0
3751,1.000000,1.000000e+00,1.000000,1.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.0,1.000000,1.000000,1.0,1.0,1.0,1.000000,1.000000e+00,1.0,0.0

In [ ]:
import scipy.sparse as sp
from scipy.sparse.linalg import svds

In [ ]:
r=sp.csr_matrix(matrix_df.to_numpy())
u, s, vt = svds(r, k=10)
vt.shape
X_pred = u @ np.diag(s) @ vt

In [ ]:
vt.shape

(10, 3752)

In [ ]:
def recomend_for_new_user(ratings:dict):
  ids=list(ratings.keys())
  rate=list(ratings.values())
  items=np.where(np.isin(matrix_df.columns, ids))[0]
  item_vecs = vt[:, items].T
  p_new, _, _, _ = np.linalg.lstsq(item_vecs, rate, rcond=None)
  predictions = p_new @ (np.diag(s) @ vt)
  #predictions = np.clip(predictions, 1, 10)
  predictions[items] = -1
  return np.argsort(predictions)[-10:][::-1]

In [ ]:
rec=recomend_for_new_user({12:10,115:10})
ids=matrix_df.T.iloc[rec].index.tolist()
movies_df[movies_df['id'].isin(ids)]

,id,title,overview,runtime,budget,revenue,vote_average,popularity,status,tagline,adult,video,genres
1,11,Star Wars,Princess Leia is captured and held hostage by ...,121.0,11000000.0,7.753980e+08,8.202,23.1666,Released,"A long time ago in a galaxy far, far away...",0,0,"Adventure,Action,Science Fiction"
221,595,To Kill a Mockingbird,"Scout Finch, 6, and her older brother Jem live...",129.0,2000000.0,1.312985e+07,7.992,4.5178,Released,A father must expose his children to a small t...,0,0,Drama
224,599,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,110.0,1752000.0,5.000000e+06,8.283,5.6366,Released,A Hollywood Story.,0,0,Drama
382,947,Lawrence of Arabia,"During World War I, English officer Thomas Edw...",228.0,15000000.0,7.000000e+07,7.995,6.7630,Released,Nothing is written.,0,0,"Adventure,History,War"
468,1585,It's a Wonderful Life,George Bailey has spent his entire life giving...,130.0,3180000.0,9.644124e+06,8.276,9.2489,Released,It's a wonderful laugh! It's a wonderful love!,0,0,"Fantasy,Drama,Family"
6622,533535,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,128.0,200000000.0,1.338074e+09,7.560,25.5398,Released,Come together.,0,0,"Action,Comedy,Science Fiction"
7290,666277,Past Lives,"After decades apart, childhood friends Nora an...",106.0,12000000.0,2.812665e+07,7.700,9.9269,Released,NaN,0,0,"Drama,Romance"
8046,930564,Saltburn,Struggling to find his place at Oxford Univers...,131.0,20000000.0,2.101374e+07,6.965,7.7097,Released,We're all about to lose our minds.,0,0,"Drama,Comedy,Thriller"
8291,1000837,I'm Still Here,A woman married to a former politician during ...,138.0,8000000.0,3.636157e+07,7.900,5.5125,Released,"When a mother's courage defies tyranny, hope i...",0,0,"Drama,History"
8333,1013850,A Real Pain,Mismatched cousins David and Benji reunite for...,90.0,3000000.0,2.485603e+07,6.800,4.9993,Released,Join the family.,0,0,"Drama,Comedy"

In [ ]:
def calculate_ranking_metrics(R_true, R_pred, k=10):
    """
    Метрики ранжирования для топ-k рекомендаций
    """
    n_users = R_true.shape[0]
    precisions = []
    recalls = []
    ndcg_scores = []

    for user in range(n_users):
        true_ratings = R_true[user]
        pred_ratings = R_pred[user]
        relevant_items = np.where(true_ratings > 7)[0]
        if len(relevant_items) == 0:
            continue
        top_k_indices = np.argsort(pred_ratings)[-k:][::-1]
        relevant_in_topk = len(set(top_k_indices) & set(relevant_items))

        precision = relevant_in_topk / k
        precisions.append(precision)


        recall = relevant_in_topk / len(relevant_items)
        recalls.append(recall)


    ranking_metrics = {
        f'Precision@{k}': np.mean(precisions),
        f'Recall@{k}': np.mean(recalls),
    }

    return ranking_metrics

In [ ]:
calculate_ranking_metrics(matrix_df.to_numpy(),X_pred)

{'Precision@10': np.float64(0.06813048933500629),
 'Recall@10': np.float64(0.3375638553404356)}